In [2]:
import pandas as pd 
import numpy as np
import os as os

def good(a,b):
    s = int(input("Enter your age here: "))
    if s>18:
        print('Hi')
    else:
        print('Bye')
    print('The reverse of the number is: ')    
    z = s%10
    print(z)
    
#THis is a code trying to implement the functions present in the numpy pacakage and the pandas package , meant as a basic introduction to the basics of the both pacakages 
x =  np.array([3,4,5,6,7])

y =  pd.array([7,8,9,0,3]) 

print('','Arrays present = ',x,y, '\n',np.concatenate((x,y)),"\n",  x.sum() + y.sum(),'\n', x.mean() + y.mean(), '\n', np.vstack((x,y) ),'\n', np.hstack((x,y) ))


 Arrays present =  [3 4 5 6 7] <IntegerArray>
[7, 8, 9, 0, 3]
Length: 5, dtype: Int64 
 [3 4 5 6 7 7 8 9 0 3] 
 52 
 10.4 
 [[3 4 5 6 7]
 [7 8 9 0 3]] 
 [3 4 5 6 7 7 8 9 0 3]


In [3]:
y =  {'Mohammad': [1,2,3,4], 'Zaid': [7,8,9,0], 'Furqan': [3,4,5,6]}
print(pd.Series(y))
h= pd.DataFrame(y,['Chemistry','Maths','Physics','Hindi'])
print(h)

h[h>4]

Mohammad    [1, 2, 3, 4]
Zaid        [7, 8, 9, 0]
Furqan      [3, 4, 5, 6]
dtype: object
           Mohammad  Zaid  Furqan
Chemistry         1     7       3
Maths             2     8       4
Physics           3     9       5
Hindi             4     0       6


,Mohammad,Zaid,Furqan
Chemistry,NaN,7.0,NaN
Maths,NaN,8.0,NaN
Physics,NaN,9.0,5.0
Hindi,NaN,NaN,6.0


In [1]:
d = {'name':'Zaid', 'age':20}
print(d['name'])          # => 'Zaid'
d['city'] = 'Srinagar'    # add
print('age' in d)         # => True
for k, v in d.items():
    print(k, v)

text = "hello hello world"
counts = {}
for w in text.split():
    counts[w] = counts.get(w, 0) + 1
print(counts)  # => {'hello': 2, 'world': 1}


Zaid
True
name Zaid
age 20
city Srinagar
{'hello': 2, 'world': 1}
